# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: CICD deploy to github package

on:
  push:
    branches:
      - "develop"
      - "staging"
      - "production"

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: set environment variable for develop
        if: github.ref == 'refs/heads/develop'
        run: echo "BUILD_PROFILE=develop" >> $GITHUB_ENV

      - name: set environment variable for staging
        if: github.ref == 'refs/heads/staging'
        run: echo "BUILD_PROFILE=staging" >> $GITHUB_ENV

      - name: set environment variable for production
        if: github.ref == 'refs/heads/production'
        run: echo "BUILD_PROFILE=production" >> $GITHUB_ENV

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -P"${BUILD_PROFILE}" --file pom.xml
        env:
          GITHUB_ACTOR: ${{ vars.ACTOR }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
